//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingredientsInRecipe
    {
        public int RecipeID { get; set; }
        public int IngredientID { get; set; }
        public Nullable<int> Order { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual recipe recipe { get; set; }
    }
}
